name: Release Builds

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
        cache: false

    - name: Run docker build
      run: |
        go run build/ci.go docker -platform linux/amd64,linux/arm64

  linux:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
        cache: false

    - name: Run build
      run: |
        go run build/ci.go install
